### ISSUE TITLE
Wildcard certificates failing at API

### ISSUE THREAD

**Issue by dupsatou** [silkeh/pdns_api.sh#29] opened 2020-09-15 00:00 UTC
When trying to create a certificate with a wildcard as a SAN (or a wildcard cert with the main domain as a SAN) I get a 400 Bad Request error.  If I create and validate the main domain by itself and re-run it later with just the wildcard added it works.  But when I come back later and try to renew the whole certificate again it fails.

```# INFO: Using main config file /etc/dehydrated/config
Processing *.example.org with alternative names: example.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Dec 13 22:15:56 2020 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for example.org
 + Handling authorization for example.org
 + 2 pending challenge(s)
 + Deploying challenge tokens...
Error: API error: curl: (22) The requested URL returned error: 400 Bad Request
ERROR: deploy_challenge hook returned with non-zero exit
```

domains.txt:
```
example.org *.example.org > example.org
```

I can also swap the main domain and wildcard - it still has the issue.

I can try to work on and contribute but I wanted to be sure its not user error here first...  is this a known issue or am I doing something wrong?

**Comment by dupsatou** [comment] 2020-09-15 14:08
Running with debug:
```
API version: 1
PDNS server: localhost
Zones: example.org
Suffix: ""
# Domain
Name:  _acme-challenge.example.org.
Token: 58cAdbaug4P0Zk1Ns6KgmpPt8Ejn3eICR85i-qLO69E kwBxFmymY2KyMYmpXNOMBnMMqqQXJpdzEL_cvX6D_Yc
Zone:  example.org.
# Request
Method: PATCH
URL: http://dns0.its.ou.edu:8081/api/v1/servers/localhost/zones/example.org.
Data: {"rrsets": [{
    "name": "_acme-challenge.example.org.",
    "type": "TXT",
    "ttl": 1,
    "records": [{
    "content": "\"58cAdbaug4P0Zk1Ns6KgmpPt8Ejn3eICR85i-qLO69E\"",
    "disabled": false,
    "set-ptr": false

    }{
    "content": "\"kwBxFmymY2KyMYmpXNOMBnMMqqQXJpdzEL_cvX6D_Yc\"",
    "disabled": false,
    "set-ptr": false

    }],
    "changetype": "REPLACE"
  }]}
Response: curl: (22) The requested URL returned error: 400 Bad Request
Error: API error: curl: (22) The requested URL returned error: 400 Bad Request
ERROR: deploy_challenge hook returned with non-zero exit code
Hook: exit_hook
```

**Comment by silkeh** [comment] 2020-09-15 14:50
Thanks! That should be enough to reproduce this. I'll take a closer look at it tomorrow.

**Comment by dupsatou** [comment] 2020-09-15 15:30
Awesome - happy to help or provide more info.  I was trying to figure out if it was me somewhere - like a version or config setting or something.  If you have trouble reproducing let me know and I'm happy to experiment and gather more info.  Thank you!

**Comment by silkeh** [comment] 2020-09-16 11:48
Ok, so the issue is a missing comma between the records, which points to [this line](https://github.com/silkeh/pdns_api.sh/blob/master/pdns_api.sh#L300) introduced with #17.

However, I am only able to reproduce this on Bash versions lower than 4.1. Can you confirm this is the case?

**Comment by silkeh** [comment] 2020-09-16 12:05
I have created a branch [`test-fixes`](https://github.com/silkeh/pdns_api.sh/tree/test-fixes) that includes a fix for this issue. It would be helpful to see the following:

- Do all tests pass? (`VERBOSE=yes ./test.sh`)
- Do you still have the issue with this version?

**Comment by dupsatou** [comment] 2020-09-16 12:10
```
[admin@example.org ~]$ bash --version
GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[admin@example.org ~]$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarc
h:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noar
ch
Distributor ID: CentOS
Description:    CentOS release 6.10 (Final)
Release:        6.10
Codename:       Final
```


I'll take a look at the test

**Comment by dupsatou** [comment] 2020-09-17 03:43
running that test on the version I had previously failed a few places -- running it on your new branch though passes on all tests.

Running it now with your test-fixes branch seems to be successful!  Thank you!

**Comment by silkeh** [comment] 2021-02-13 15:02
Whoops, seems like I forgot to close this one. Thanks again for reporting the issue!

**Closed by silkeh** 2021-02-13 15:02 UTC
